FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY app.json ./
COPY App.js ./
COPY babel.config.js ./
COPY global.css ./
COPY index.js ./
COPY metro.config.js ./
COPY tailwind.config.js ./
COPY assets ./assets
COPY src ./src

ARG EXPO_PUBLIC_API_BASE_URL=http://localhost:3001
ENV EXPO_PUBLIC_API_BASE_URL=${EXPO_PUBLIC_API_BASE_URL}

RUN npx expo export --platform web

FROM nginx:1.27-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
